ClaroGrandesSuperficies/Models/User/Rol.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Core.Models.User
{
	public class Rol : Entity
	{
		public string Name { get; set; }
	}
}

ClaroGrandesSuperficies/Models/User/User.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;



namespace Core.Models.User
{
    public class User : Entity
	{
        [DisplayName("Documento")]
		public string Document { get; set; }
        [DisplayName("Nombres")]
        public string Names { get; set; }
        [DisplayName("Apellidos")]
        public string LastName { get; set; }
        [DisplayName("Telefono 1")]
        public string Phone1 { get; set; }
        //[DisplayName("Telefono 2")]
        //public string Phone2 { get; set; }
        //[DisplayName("Telefono 3")]
        //public string Phone3 { get; set; }
        [DisplayName("Correo")]
        public string Email { get; set; }
        [DisplayName("Estado")]
        public bool Status { get; set; }
        [DisplayName("password")]
        public string PassWord { get; set; }

        public string Campaign { get; set; }  
        
        public DateTime? LoginDate { get; set; }       
        
        public List<UserRol> UserRol { get; set; }
        

    }
}

ClaroGrandesSuperficies/Models/User/UserRol.cs
using Core.Models.Common;
using Core.Models.configuration;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Core.Models.User
{
	public class UserRol : Entity
	{
		public Guid RolId { get; set; }
		public Guid UserId { get; set; }

		[ForeignKey("RolId")]
		public Rol Rol  { get; set; }

		[ForeignKey("UserId")]
		public User User { get; set; }
	}
}

ClaroGrandesSuperficies/Controllers/UsersController.cs
using System;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ClaroGrandesSuperficies.Models;
using Core.Models.Security;
using Core.Models.User;
using PagedList;

namespace ClaroGrandesSuperficies.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class UsersController : Controller
    {
        private ContextModel db = new ContextModel();

        // GET: Users
        public ActionResult Index(int? page, string filterUserByDocument, string filterUserByName)
        {
            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PaginationUsers"]);

            IQueryable<User> listUsers = from u in db.Users
                                         select u;

            if (!string.IsNullOrEmpty(filterUserByDocument))
            {
                string document = filterUserByDocument.Trim();
                listUsers = listUsers.Where(u => u.Document == document);
            }
            if (!string.IsNullOrEmpty(filterUserByName))
            {
                string name = filterUserByName.Trim();
                listUsers = listUsers.Where(u => u.Names.Contains(name) || name == null);
            }

            int pageNumber = (page ?? 1);

            return View(listUsers.OrderBy(u => u.Names).ToPagedList(pageNumber, pageSize));
        }

        // GET: Users/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Document,Names,LastName,Phone1,Phone2,Phone3,Email,Status,PassWord,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Id = Guid.NewGuid();
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Document,Names,LastName,Phone1,Phone2,Phone3,Email,Status,PassWord,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Roles(Guid Id)
        {
            User Usuario = db.Users.Find(Id);
            if (Id == null || Usuario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Name = Usuario.Names;
            ViewBag.Id = Id;
            ViewBag.Email = Usuario.Email;
            ViewBag.Pass = Usuario.PassWord;
            ViewBag.UsersRol = db.UserRols.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Rols, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Roles([Bind(Include = "Id,RolId,UserId")] UserRol userRol, string Name, string password, string email)
        {
            if (ModelState.IsValid)
            {
                var Exist = db.UserRols
                    .Where(
                    c => c.UserId == userRol.UserId &&
                    c.RolId == userRol.RolId
                ).FirstOrDefault();

                if (Exist != null)
                {
                    ModelState.AddModelError("RolId", "este permiso ya fue asignado");
                }
                else
                {
                    User user = db.Users.Where(x => x.Id == userRol.UserId).FirstOrDefault();

                    if (user != null)
                    {
                        user.PassWord = password.Trim();
                        user.Email = email.Trim();
                        db.Entry(user).State = EntityState.Modified;                        
                        userRol.Id = Guid.NewGuid();
                        db.UserRols.Add(userRol);
                        db.SaveChanges();
                        return RedirectToAction("Roles", new { Id = userRol.UserId });
                    }
                 
                }


            }
            var Id = userRol.UserId;
            ViewBag.Email = email.Trim();
            ViewBag.Pass = password.Trim();
            ViewBag.Name = Name;
            ViewBag.Id = Id;
            ViewBag.UsersRol = db.UserRols.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Rols, "Id", "Name");
            return View("Roles");
        }

        [HttpPost, ActionName("DeleteRol")]
        [ValidateAntiForgeryToken]
        public ActionResult RolesDeleteConfirmed(Guid id)
        {
            UserRol UsusarioRol = db.UserRols.Find(id);
            var UserId = UsusarioRol.UserId;
            db.UserRols.Remove(UsusarioRol);
            db.SaveChanges();
            return RedirectToAction("Roles", new { Id = UserId });
        }


    }
}

ClaroGrandesSuperficies/Views/Users/Create.cshtml
@model Core.Models.User.User

@{
    ViewBag.Title = "Create";
}

@{
    ViewBag._Active = "Create";
    ViewBag._Panel = "Home";
}



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Crear Usuario</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Document, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Document, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Names, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Names, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Names, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Phone1, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Phone1, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Phone1, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Phone2, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Phone2, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Phone2, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Phone3, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Phone3, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Phone3, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Status)

                                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.PasswordFor(model => model.PassWord, new { @class = "form-control" })

                                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </div>
</div>

ClaroGrandesSuperficies/Views/Users/Delete.cshtml
@model Core.Models.User.User

@{
    ViewBag.Title = "Delete";
}

@{
	ViewBag._Active = "Delete";
	ViewBag._Panel = "Home";
}


<div class="box box-danger">
	<div class="box-header with-border">
		<h3 class="box-title">¿Esta seguro que desea eliminar este elemento?</h3>
	</div><!-- /.box-header -->
	<div class="box-body">
		<div class="row">
		<div class="col-md-12 col-xs-12 col-sm-12">
			<table id="tabla" class="table table-bordered table-hover">
				<tbody>
																												<tr>
								<th>
									@Html.DisplayNameFor(model => model.Document)
								</th>

								<td>
									@Html.DisplayFor(model => model.Document)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.Names)
								</th>

								<td>
									@Html.DisplayFor(model => model.Names)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.LastName)
								</th>

								<td>
									@Html.DisplayFor(model => model.LastName)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.Phone1)
								</th>

								<td>
									@Html.DisplayFor(model => model.Phone1)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.Phone2)
								</th>

								<td>
									@Html.DisplayFor(model => model.Phone2)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.Phone3)
								</th>

								<td>
									@Html.DisplayFor(model => model.Phone3)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.Email)
								</th>

								<td>
									@Html.DisplayFor(model => model.Email)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.Status)
								</th>

								<td>
									@Html.DisplayFor(model => model.Status)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.PassWord)
								</th>

								<td>
									@Html.DisplayFor(model => model.PassWord)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.CreatedAt)
								</th>

								<td>
									@Html.DisplayFor(model => model.CreatedAt)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.UpdatedAt)
								</th>

								<td>
									@Html.DisplayFor(model => model.UpdatedAt)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.DeletedAt)
								</th>

								<td>
									@Html.DisplayFor(model => model.DeletedAt)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.CreatedBy)
								</th>

								<td>
									@Html.DisplayFor(model => model.CreatedBy)
								</td>
							</tr>

																					<tr>
								<th>
									@Html.DisplayNameFor(model => model.UpdatedBy)
								</th>

								<td>
									@Html.DisplayFor(model => model.UpdatedBy)
								</td>
							</tr>

											</tbody>
			</table>
			</div>
		</div>
	</div>
</div>

		@using (Html.BeginForm()) {
			@Html.AntiForgeryToken()

			<div class="form-actions no-color">
				<input type="submit" value="Delete" class="btn btn-danger" /> 
				@Html.ActionLink("Regresar", "Index",null, new { @class = "btn btn-default" })
			</div>
		}
</div>

ClaroGrandesSuperficies/Views/Users/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<Core.Models.User.User>

@{
    ViewBag.Title = "Index";
}

@{
    ViewBag._Active = "Index";
    ViewBag._Panel = "Home";
}

<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Listar</h3>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-xs-12 col-md-12 col-lg-12">
                @using (Html.BeginForm("Index", "Users", FormMethod.Post))
                {
                    <div class=" col-md-3 form-group">
                        <label>Filtrar usuario por documento</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            @Html.TextBox("FilterUserByDocument", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class=" col-md-3 form-group">
                        <label>Filtrar usuario por nombres</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            @Html.TextBox("FilterUserByName", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                        </div>
                    </div>


                    <div class="col-md-6 inline-form form-group">
                        <label for=""> Acciones </label>
                        <div class="input-group">
                            <input type="submit" class="btn btn-primary" id="btnCon" value="consultar">
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>




<div class="box box-danger">
    <div class="box-header with-border">
        <p class="input-group-addon alert "><b>LISTADO DE EMPLEADOS</b> </p>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <table id="tabla" class="table table-bordered table-hover table-responsive table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.First().Document)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.First().Names)
                            </th>
                            <th>
                                Campañas
                            </th>

                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Document)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Names)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Campaign)
                                </td>


                                <td>
                                    @*@Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-success" })*@
                                    @*@Html.ActionLink("Detalle", "Details", new { id = item.Id }, new { @class = "btn btn-xs btn-default" })*@
                                    @Html.ActionLink("Perfiles", "Roles", new { id = item.Id }, new { @class = "btn btn-xs btn-warning" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "listUsers-grid" }))
            </div>
        </div>
    </div>
</div>

ClaroGrandesSuperficies/Views/Users/Roles.cshtml
@model Core.Models.User.UserRol



@{
    ViewBag.Title = "Index";
}

@{
    ViewBag._Active = "Roles";
    ViewBag._Panel = "User";
}


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Usuario: <strong>@ViewBag.Name</strong></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">

                @using (Html.BeginForm("Roles", "Users"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.RolId, "Nombre del Rol", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("RolId", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.RolId, "", new { @class = "text-danger" })
                                <label id="errorRol"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.User.Email, "Correo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="email" name="email" value="@ViewBag.Email" class="form-control" id="email" />
                                <label id="errorEmail"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.User.PassWord, "Contraseña", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="password" name="password" value="@ViewBag.Pass" class="form-control" id="pass" />
                                <label id="errorPass"></label>
                            </div>
                        </div>
                        <input type="hidden" name="UserId" value="@ViewBag.Id" />
                        <input type="hidden" name="Name" value="@ViewBag.Name" />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" id="createRol" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Lista de Roles</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                Nombre del Rol
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (Core.Models.User.UserRol item in ViewBag.UsersRol)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Rol.Name)
                                </td>
                                <td>
                                    @using (Html.BeginForm("DeleteRol", "Users", new { Id = item.Id }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-actions no-color">
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                        </div>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger" })
</div>

@section Scripts {

    <script>

        $('body').on('click', '#createRol', function () {

            var rol = $('#RolId option:selected').val();
            var email = $('#email').val();
            var pass = $('#pass').val();

            console.log(email);
            console.log(pass);

            if (rol === "") {
                $('#errorRol').text('El campo rol es requerido').css('color', 'red');
                return false;
            }

            if (email === "") {
                $('#errorEmail').text('El campo correo es requerido').css('color', 'red');
                return false;
            }

            if (pass === "") {
                $('#errorPass').text('El campo contraseña es requerido').css('color', 'red');
                return false;
            }
        });

        // Procedimiento para remover las alertas.
        $('body').on('change', '#RolId', function () {
            $('#errorRol').text('');          
        });
        $('body').on('blur', '#email', function () {
            $('#errorEmail').text('');
        });
        $('body').on('blur', '#pass', function () {
            $('#errorPass').text('');
        });

    </script>
}