ClaroGrandesSuperficies/Controllers/AccountsController.cs
using Core.Models.Security;
using System.Web.Mvc;


namespace ClaroGrandesSuperficies.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Index()
        {
            if (SessionPersister.Id != null)
                return RedirectToAction("Home","Sales",null);

            return View();
        }



        [HttpPost]
        public ActionResult Login(AccountsViewModel avm)
        {

            AccountsModel am = new AccountsModel();
            Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);
            if (string.IsNullOrEmpty(avm.Accounts.UserName) || string.IsNullOrEmpty(avm.Accounts.Password) || ResultUser == null)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("index");
            }
            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = ResultUser.Id;           

            return RedirectToAction("Home", "Sales", null);

        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            return View("index");
        }


        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

ClaroGrandesSuperficies/Controllers/ConfigurationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClaroGrandesSuperficies.Models;
using Core.Models.configuration;
using Core.Models.Security;

namespace ClaroGrandesSuperficies.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class ConfigurationsController : Controller
    {

        private ContextModel db = new ContextModel();



        // GET: Configurations

        public ActionResult Index(Guid? Category, string Name)
        {
            Category ActualCategory = db.Categories.Find(Category);

            if (ActualCategory == null || ActualCategory.CanChanged == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "la category no existe.");
            }

            ViewBag.Name = ActualCategory.Name;
            ViewBag.FName = Name;
            ViewBag.ColumName = ActualCategory.Name;
            ViewBag.Category = Category;
            var configurations = db.Configurations.Include(c => c.Category).Where(C => C.CategoriesId == Category);
            if (Name != null && Name.Trim() != "")
            {
                configurations = configurations.Where(c => c.Name.Contains(Name));
            }

            return View(configurations.ToList());
        }

        // GET: Configurations/Details/5
        //[CustomAuthorize(Roles = "Admin")]
        [CustomAuthorize(Roles = "7E6B69E8-87D0-419F-9054-02FCA94D5A73")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Configuration configurations = db.Configurations.Include(c => c.Category).Where(c => c.Id == id).FirstOrDefault();
            if (configurations == null)
            {
                return HttpNotFound();
            }
            return View(configurations);
        }

        // GET: Configurations/Create
        //[CustomAuthorize(Roles = "Admin")]
        [CustomAuthorize]
        public ActionResult Create(Guid? Category)
        {
            Category ActualCategory = db.Categories.Find(Category);
            if (ActualCategory == null || ActualCategory.CanChanged == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "La Categoria no existe.");
            }

            ViewBag.Category = Category;
            ViewBag.Name = ActualCategory.Name;
            ViewBag.Guid = ActualCategory.Name;
            ViewBag.Configtype = ActualCategory.Name;
            ViewBag.ColumName = ActualCategory.Name;
            return View();
        }

        // POST: Configurations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Status,CategoriesId,Description,GuidId")] Configuration configurations)
        {
            if (ModelState.IsValid)
            {

                db.Configurations.Add(configurations);
                db.SaveChanges();
                return RedirectToAction("Index", new { Category = configurations.CategoriesId });
            }
            ViewBag.GuidId = new SelectList(db.Configurations, "Id", "Name", configurations.GuidId);
            ViewBag.CategoriesId = new SelectList(db.Categories, "Id", "Name", configurations.CategoriesId);
            return View(configurations);
        }

        // GET: Configurations/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Configuration configurations = db.Configurations.Find(id);
            if (configurations == null)
            {
                return HttpNotFound();
            }

            return View(configurations);
        }

        // POST: Configurations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Status,Description,GuidId")] Configuration configurations)
        {
            if (ModelState.IsValid)
            {

                db.Entry(configurations).State = EntityState.Modified;
                db.Entry(configurations).Property(c => c.CategoriesId).IsModified = false;
                db.SaveChanges();

                ContextModel db2 = new ContextModel();
                var CategoryId = db2.Configurations.Find(configurations.Id).CategoriesId;


                return RedirectToAction("Index", new { Category = CategoryId });
            }

            return View(configurations);
        }

        [CustomAuthorize]       
        public ActionResult ListEmail()
        {
            List<Configuration> configuration = db.Configurations.Include(c => c.Category).Where(x => x.CategoriesId == new Guid("2F75E8B6-C8B5-44D7-9BDC-1C90B6E55EC8")
                                                || x.CategoriesId == new Guid("AACD2C34-B89B-412A-8037-F0596F64420B")).ToList();
            return View(configuration);
        }


        public ActionResult CreateEmail()
        {
            ViewBag.CategoriesId = new SelectList(db.Categories.OrderBy(x => x.Name).Where(x => x.Id == new Guid("2F75E8B6-C8B5-44D7-9BDC-1C90B6E55EC8")
                                                || x.Id == new Guid("AACD2C34-B89B-412A-8037-F0596F64420B")), "Id", "Name");

            return View();
        }

        [HttpPost]
        public ActionResult CreateEmail(Configuration configurations)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    configurations.Name = configurations.Name.Trim();
                    db.Configurations.Add(configurations);
                    db.SaveChanges();
                    return RedirectToAction("ListEmail");
                }
                catch (Exception)
                {

                    throw;
                }
            }

            ViewBag.CategoriesId = new SelectList(db.Categories.OrderBy(x => x.Name).Where(x => x.Id == new Guid("2F75E8B6-C8B5-44D7-9BDC-1C90B6E55EC8")
                                              || x.Id == new Guid("AACD2C34-B89B-412A-8037-F0596F64420B")), "Id", "Name", configurations.CategoriesId);
            return View(configurations);
        }

        public ActionResult EditEmail(Guid? Id)
        {
            Configuration configuration = db.Configurations.Find(Id);

            if (configuration == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoriesId = new SelectList(db.Categories.OrderBy(x => x.Name).Where(x => x.Id == new Guid("2F75E8B6-C8B5-44D7-9BDC-1C90B6E55EC8")
                                                || x.Id == new Guid("AACD2C34-B89B-412A-8037-F0596F64420B")), "Id", "Name", configuration.CategoriesId);

            return View(configuration);
        }

        [HttpPost]
        public ActionResult EditEmail(Configuration configuration)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Configuration model = db.Configurations.Where(x => x.Id == configuration.Id).FirstOrDefault();
                    model.Name = configuration.Name.Trim();
                    model.Description = configuration.Description;
                    model.Status = configuration.Status;
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("ListEmail");

                }
                catch (Exception)
                {

                    throw;
                }
            }

            ViewBag.CategoriesId = new SelectList(db.Categories.OrderBy(x => x.Name).Where(x => x.Id == new Guid("2F75E8B6-C8B5-44D7-9BDC-1C90B6E55EC8")
                                                || x.Id == new Guid("AACD2C34-B89B-412A-8037-F0596F64420B")), "Id", "Name", configuration.CategoriesId);

            return View(configuration);
        }



        // GET: Configurations/Delete/5
        public ActionResult Delete(Guid? id, int Configtype = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Configuration configurations = db.Configurations.Include(c => c.Category).Where(c => c.Id == id).FirstOrDefault();
            if (configurations == null)
            {
                return HttpNotFound();
            }

            return View(configurations);
        }

        // POST: Configurations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id, int Configtype = 0)
        {
            Configuration configurations = db.Configurations.Find(id);
            db.Configurations.Remove(configurations);
            db.SaveChanges();
            return RedirectToAction("Index", new { Category = configurations.CategoriesId });
        }

        public JsonResult MailCheck(string email, Guid? category, string action, Guid? CofigurationId)
        {
            if (action == "1")
            {
                // Validación al crear.
                var resp = db.Configurations.Where(x => x.Name.Trim() == email.Trim() && x.CategoriesId == category).FirstOrDefault();
                if (resp != null)
                {
                    return Json(new { status = false }, JsonRequestBehavior.AllowGet);

ClaroGrandesSuperficies/Views/Shared/_Layout.cshtml
@using Core.Models.Security
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Uno27 Inventario control de Equipos</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    @*<meta http-equiv="refresh" content="2" />*@
    @Styles.Render("~/Content/css")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link href="~/Content/" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.min.css" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body class="hold-transition skin-red sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Home","Sales")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>U</b>27</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Inventario</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </nav>
        </header>

        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Content/Images/logo.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <br />
                        <p>@SessionPersister.UserName</p>
                    </div>
                </div>
                <!-- search form -->

                @Html.Partial("_Menu")

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            @Html.Partial("_Footer")
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

                <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
            </ul>
            <!-- Tab panes -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->

    @Scripts.Render("~/bundles/js")
    <script src="~/Content/adminlte/js/adminlte.min.js"></script>
    <script src="~/Content/adminlte/js/demo.js"></script>
    <script>
        const BaseUrl =  @Html.Raw(HttpUtility.JavaScriptStringEncode(Url.Content("~/"), true));
    </script>

    @*<script src="~/Scripts/app/app.js"></script>*@
    @RenderSection("scripts", required: false)
</body>
</html>

ClaroGrandesSuperficies/Views/Shared/_Menu.cshtml
﻿@using Core.Models.Security
<!-- /.search form -->
<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu" data-widget="tree">

    <li class="header">Administración</li>

    <!-- #region POINT OF CARE MENU -->
    @if (SessionPersister.HasRol("Administrador"))
    {
        <li class="treeview @if (ViewBag._Panel == "PointOfCare") { Write("active"); } ">
            <a href="#">
                <i class="fa  fa-bank"></i> <span>Sedes</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                    <a href="@Url.Action("create", "PointOfCares")"><i class="fa fa-circle-o"></i>Ingresar</a>
                </li>
                <li class=" @if (ViewBag._Active == "index") { Write("active"); } ">
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("index", "PointOfCares")"><i class="fa fa-circle-o"></i>Listar</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->
    <!-- #region USUARIOS -->
    @if (SessionPersister.HasRol("Administrador"))
    {
        <li class="treeview @if (ViewBag._Panel == "Users") { Write("active"); } ">
            <a href="#">
                <i class="fa fa-street-view"></i> <span>Usuarios</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">              
                <li>
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("index", "Users")"><i class="fa fa-circle-o"></i>Listar Usuarios</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->
    <!-- #region TYPE OF PRODUCTS MENU -->
    @if (SessionPersister.HasRol("Administrador"))
    {
        <li class="treeview @if (ViewBag._Panel == "TypeProduct") { Write("active"); } ">
            <a href="#">
                <i class="fa fa-cubes"></i> <span>Categoría de productos</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="@Url.Action("create", "Configurations", new { Category = "4f853039-b77e-4546-a31b-4963e487160c" })"><i class="fa fa-circle-o"></i>Ingresar</a>
                </li>
                <li>
                    <a href="@Url.Action("index", "Configurations", new { Category = "4f853039-b77e-4546-a31b-4963e487160c" })"><i class="fa fa-circle-o"></i>Listar</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->
    <!-- #region PRODUCT -->
    @if (SessionPersister.HasRol("Administrador"))
    {
        <li class="treeview @if (ViewBag._Panel == "Product") { Write("active"); } ">
            <a href="#">
                <i class="fa  fa-briefcase"></i> <span>Productos</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="@Url.Action("create", "Products")"><i class="fa fa-circle-o"></i>Ingresar</a>
                </li>
                <li>
                    <a href="@Url.Action("index", "Products")"><i class="fa fa-circle-o"></i>Listar</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->
    <!-- #region Supplier MENU -->
    @if (SessionPersister.HasRol("Administrador"))
    {
        <li class="treeview @if (ViewBag._Panel == "TypeProduct") { Write("active"); } ">
            <a href="#">
                <i class="fa fa-cubes"></i> <span>Proveedores</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="@Url.Action("create", "Suppliers")"><i class="fa fa-circle-o"></i>Crear</a>
                </li>
                <li>
                    <a href="@Url.Action("index", "Suppliers")"><i class="fa fa-circle-o"></i>Listar</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->
    <!-- #region INVENTORY -->
    @if (SessionPersister.HasRol("Administrador") || SessionPersister.HasRol("Supervisor") || SessionPersister.HasRol("Vendedor"))
    {
        <li class="treeview @if (ViewBag._Panel == "Inventory") { Write("active"); } ">
            <a href="#">
                <i class="fa fa-shopping-cart"></i> <span>Ordenes</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("create", "OrderIncomes")"><i class="fa fa-circle-o"></i>Ingresar</a>
                </li>
                <li>
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("index", "OrderIncomes")"><i class="fa fa-circle-o"></i>Listar</a>
                </li>

                @if (SessionPersister.HasRol("Vendedor"))
                {
                    <li>
                        <!-- Sending guid of farmer type -->
                        <a href="@Url.Action("Index2", "Inventories")"><i class="fa fa-circle-o"></i>Mi inventario</a>
                    </li>
                }
            </ul>
        </li>
    }
    <!-- #endregion -->
    <!-- #region SALES -->
    @if (SessionPersister.Id != null)
    {
        <li class="treeview @if (ViewBag._Panel == "Sales") { Write("active"); } ">
            <a href="#">
                <i class="fa  fa-bank"></i> <span>Movimientos</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("create", "Sales")"><i class="fa fa-circle-o"></i>Salidas/Devoluciones</a>
                </li>
                <li>
                    <a href="@Url.Action("InventoryTransferList", "OrderIncomes")"><i class="fa fa-circle-o"></i>Traslado de Inventario</a>
                </li>
                <li>
                    <a href="@Url.Action("CreateAssignment", "Sales")"><i class="fa fa-circle-o"></i>Asignación de Equipos</a>
                </li>

            </ul>
        </li>
    }
    <!-- #endregion -->

    <!-- #region Reportes -->
    @*@if (SessionPersister.HasRol("Administrador") || SessionPersister.HasRol("Supervisor"))
    {
        <li class="treeview @if (ViewBag._Panel == "Users") { Write("active"); } ">
            <a href="#">
                <i class="fa   fa-book"></i> <span>Reportes</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="@Url.Action("Outputs", "Reports")"><i class="fa fa-circle-o"></i>Salidas de Inventario</a>
                </li>
                <li>
                    <a href="@Url.Action("Returns", "Reports")"><i class="fa fa-circle-o"></i>Devoluciones de Inventario</a>
                </li>

            </ul>
        </li>
    }*@
    <!-- #endregion -->

    <!-- #region CheckList -->
    @if (SessionPersister.HasRol("Vendedor"))
    {
        <li class="treeview @if (ViewBag._Panel == "Users") { Write("active"); } ">
            <a href="#">
                <i class="fa   fa-hand-pointer-o"></i> <span>CheckList</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("create", "CheckLists")"><i class="fa fa-circle-o"></i>Realizar Checklist</a>
                </li>
                <li>
                    <!-- Sending guid of farmer type -->
                    <a href="@Url.Action("index", "CheckLists")"><i class="fa fa-circle-o"></i>Listar Checklist</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->

    <!-- #region TYPE EMAILS -->
    @if (SessionPersister.HasRol("Administrador"))
    {
        <li class="treeview @if (ViewBag._Panel == "Users") { Write("active"); } ">
            <a href="#">
                <i class="fa fa-cubes"></i> <span>Agregar Correos</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="@Url.Action("CreateEmail", "Configurations")"><i class="fa fa-circle-o"></i>Nuevo Correo</a>
                </li>
                <li>
                    <a href="@Url.Action("ListEmail", "Configurations")"><i class="fa fa-circle-o"></i>Lista de Correos</a>
                </li>
            </ul>
        </li>
    }
    <!-- #endregion -->

    @if (SessionPersister.Id != null)
    {
        <li class="">
            <a href="@Url.Action("Logout", "Accounts", null)">
                <i class="fa fa-sign-out"></i>
                <span>Cerrar sesión</span>
            </a>
        </li>
    }
</ul>